### PR TITLE
Correct ansible_mounts not finding tmpfs to run 1.1.15-1.1.17

### PR DESCRIPTION
**Pull request by dgutierrez1287**
The ansible_mounts fact will only find mounts that are tied to a physical device (in most cases just the root volume) so it will not list other mounts like tmpfs that has mount option changes in 1.1.15 - 1.1.17. This change has a custom fact that will pull an all_mounts fact from mtab and return them with the same structure as the ansible_mounts fact which can then be used by those tasks for changes on tmpfs. Also since the fact is run only at the start the setup task has to be rerun for 1.1.16 and 1.1.17 in order to see any change from 1.1.15.

### CODE REVIEW

**Comment by anthcourtney** [comment]
Thanks for this PR. It seems to contain changes not related to the use of the mounts fact - can you clean up the PR so that there is isolation?

**Comment by dgutierrez1287** [comment]
Yes of course. The only addition modification is adding the .idea to the git ignore would you like that as a separate PR? Also come to think of it with the additional custom fact that needs to be placed for these tasks to work I was thinking there should be additional documentation for it but I'm not sure how you would like to handle that?

**Comment by bstock92** [comment]
Have you ran this to verify that it will achieve the desired result?

According to my [reading](https://medium.com/@jezhalford/ansible-custom-facts-1e1d1bf65db8) (and consistent with my experience), custom facts need to exist on the managed (remote) system, not on the Ansible host.

From Jez Halford's blog (see above), the implementation using ansible facts would look something like this:
```
- name: "Create custom fact directory"
  file:
    path: "/etc/ansible/facts.d"
    state: "directory"

- name: "Insert custom fact file"
  copy:
    src: files/custom.fact
    dest: /etc/ansible/facts.d/custom.fact
    mode: 0755

- name: "Re-run setup to use custom facts"
  setup: ~
```

It seems to me that this proposed change will not have the desired effect of running the fact script, since I don't see it get copied to `/etc/ansible/facts.d` on the managed host. Am I missing something?

In my particular use case (I stumbled upon this issue while researching for a similar, but different project), I find it more desirable to avoid creating (and potentially having to remove afterward) fact scripts from the managed host. So, I came up with a solution which uses the `script` module and the `from_json` jinja2 filter to achieve an effect very similar to custom facts:

```
- script: files/all_mounts.py
   register: all_mounts_result
   changed_when: false
- debug:
     msg: "{{ item.mount }}"
     with_items: "{{ all_mounts_result.stdout | from_json }}"
```

**Comment by chandanchowdhury** [comment]
Hi @bstock92,
not sure about @dgutierrez1287, but I personally have not tested the changes.

From a quick look, it seems he wanted to make more changes but could not finish for reasons.

As you have already done the research, I think you are the best person to make the changes.
Do you think you can create a pull request with all the changes?

Please let us know if we can help anyway.

**Comment by bstock92** [comment]
@chandanchowdhury I have opened a PR [here](https://github.com/anthcourtney/ansible-role-cis-amazon-linux/pull/60) for this issue.

**Pull request merged**
