### PR TITLE
Implement Missing Checks

### PR DESCRIPTION
**Pull request by gergnz**
We've fixed up/add most of the missing checks and added a few extra features (e.g. don't enable full patching, and allow 'errors' for things like IPv6; as when it is removed it errors.

Let me know if you have any questions.

### CODE REVIEW

**Comment by anthcourtney** [comment]
Many many thanks for this PR. Please give me a couple of days to digest it.

Would you be able to rebase it?

**Comment by gergnz** [comment]
> Would you be able to rebase it?

@anthcourtney it appears that there is nothing to rebase? Are you seeing some issue/conflict?

**Comment by anthcourtney** [comment]
@gergnz - Apologies (late night baby brain), I meant to ask if you could squash some of the commits into either a single commit or a series of commits which reflected functionality (with neater commit messages).

**Comment by gergnz** [comment]
Damn, I was hoping you wouldn't ask me that. It was my intention, but then time got away and I wanted to get this out the door. Yes, OK, fair call. Give me a few days to put something together that's more coherent.

**Comment by gergnz** [comment]
Hi @anthcourtney that's now 1 commit. Sorry for the long delay.

**Pull request merged**
